### ISSUE TITLE
Deprecated Flathub Guide in installation manual

### ISSUE THREAD

**Issue by mrmstn** [bottlesdevs/documentation#3]
Hi there

I just mad a flatpak update and noticed the following messages:
```
Info: com.usebottles.bottles.Locale//stable is end-of-life, with reason:
   We are exiting Flathub, please move to one of the supported packages.
Info: com.usebottles.bottles//stable is end-of-life, with reason:
   We are exiting Flathub, please move to one of the supported packages.
```

As I was looking for a new flatpak repo, I coulnd't find any new one except for the depreacted flathub link in the installation guide:
https://github.com/bottlesdevs/documentation/blob/45b2f1a867005360d504c594994add3c2a4c03a2/getting-started/installation.md#L19

I was wondering, will there be a new flatpak repo? or will you drop the flatpak support for this project?

**Comment by mirkobrombin** [comment]
> Hi there
> 
> I just mad a flatpak update and noticed the following messages:
> 
> ```
> Info: com.usebottles.bottles.Locale//stable is end-of-life, with reason:
>    We are exiting Flathub, please move to one of the supported packages.
> Info: com.usebottles.bottles//stable is end-of-life, with reason:
>    We are exiting Flathub, please move to one of the supported packages.
> ```
> 
> As I was looking for a new flatpak repo, I coulnd't find any new one except for the depreacted flathub link in the installation guide:
> https://github.com/bottlesdevs/documentation/blob/45b2f1a867005360d504c594994add3c2a4c03a2/getting-started/installation.md#L19
> 
> I was wondering, will there be a new flatpak repo? or will you drop the flatpak support for this project?

Hi, we ditched Flatpak due to lack of time and experience with that package. We are not present on other repo and for now we have simply abandoned Flatpak. So officially Bottles has no more a Flatpak package but we are available to collaborate with anyone who wants to take the responsibility of bringing it back.

More info: https://mirko.pm/blog/bottles-will-leave-flatpak/

Thanks for your feedback, I will update the documentation asap.
